# Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"khasim@gmail.com",
    "password":"12345"
}

#### User registration
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstname":"Harshit",
    "lastname":"Sai",
    "email":"harshit@gmail.com",
    "username":"harshit",
    "password":"12345"

}

#### User Logout
GET http://localhost:3000/auth/logout


###Soft delete
PATCH http://localhost:3000/auth/delete

#### create post
POST http://localhost:3000/posts/post
Content-Type: application/json

{
    "content":"XYZ",
    "postImageUrl":"https://i0.wp.com/picjumbo.com/wp-content/uploads/beautiful-nature-mountain-scenery-with-flowers-free-photo.jpg?w=2210&quality=70"
}


###
PUT http://localhost:3000/likes/69f9bf657d85ee467444a9d5

####
GET http://localhost:3000/posts/69facefb317a9b9fccfcd992

####
DELETE  http://localhost:3000/posts/69fac2b6251878f8861fa002



#### Get notification
GET http://localhost:3000/notification

#### Mark notification as read
PUT http://localhost:3000/notification/69fc2c782ea2b702138b0668/read


##### clear all notification
DELETE http://localhost:3000/notification



#### follow 
PUT http://localhost:3000/user/69fc31e1e22788b2b941126e/follow

#### Unfollow
PUT http://localhost:3000/user/69fc31e1e22788b2b941126e/unfollow