# Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"khasim@gmail.com",
    "password":"12345"
}

#### User registration
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstname":"Mohiddin",
    "lastname":"Khasim",
    "email":"khasim@gmail.com",
    "username":"Khasim",
    "password":"12345"

}

#### User Logout
GET http://localhost:3000/auth/logout


###Soft delete
PATCH http://localhost:3000/auth/delete


####
POST http://localhost:3000/posts/post
Content-Type: application/json

{
    "content":"XYZ",
    "postImageUrl":"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBw8QDg8QEA8…"
}


###
PUT http://localhost:3000/likes/69f9bc152c35ce9aaf759d06

####
GET http://localhost:3000/posts/69f9bc152c35ce9aaf759d06

####
DELETE  http://localhost:3000/posts/69f9bc152c35ce9aaf759d06